### ISSUE TITLE
Brisbane and Gold Coast, Australia

### ISSUE THREAD

**Issue by mark31** [mapzen/metroextractor-cities#136]
It would be greatly appreciated if you could make the following changes....

These bounds better define the Brisbane metropolitan area:

 "brisbane_australia": {
"bbox": {
"top": "-27.000",
"left": "152.700",
"bottom": "-27.722",
"right": "153.349"

Also a Gold Coast bounding box would be great:

 "gold_coast_australia": {
"bbox": {
"top": "-27.722",
"left": "153.130",
"bottom": "-28.200",
"right": "153.583"

Many thanks, Mark31

**Comment by heffergm** [comment]
@mark31 The changes have been made and will be available after the next processing run in ~1 week.
