### ISSUE TITLE
Current Moscow extract cropping does not cover new Moscow boundary

### ISSUE THREAD

**Issue by meule** [mapzen/metroextractor-cities#138]
![screenshot 2015-01-08 03 31 32](https://cloud.githubusercontent.com/assets/5273438/5652805/e3838d02-96e6-11e4-9bfc-70212b0b2f27.png)

**Comment by heffergm** [comment]
@meule our extracts are built at the request of users looking for specific chunks of data. Which is to say, we don't trace any explicit boundaries. If you'd like to update the Moscow bounding box I'm happy to incorporate the change.
