### ISSUE TITLE
Brisbane, Australia tweak

### ISSUE THREAD

**Issue by mark31** [mapzen/metroextractor-cities#144]
Many thanks for this great service! I want to make a very small tweak to the Brisbane southern boundary so the dataset can be joined with the Gold Coast one. There is currently a very fine gap.

"brisbane_australia": {
"bbox": {
"top": "-27.000",
"left": "152.700",
"bottom": "-27.723",
"right": "153.349"

**Comment by heffergm** [comment]
Updated here: e3709db3af247c3b1b75cf9475bf46cec6db3c2c
