### ISSUE TITLE
Vancouver

### ISSUE THREAD

**Issue by pnorman** [mapzen/metroextractor-cities#146]
Currently the Vancouver extract extends far beyond both Vancouver and Metro Vancouver.

A bounding box for Metro Vancouver is -123.725,48.995,-122.405,49.575. One for just Vancouver is -123.2900,49.1950,-123.0200,49.3200

**Comment by heffergm** [comment]
Updated: 50f6d14d8a894494e812a19f6529511e0fd28344

**Comment by pnorman** [comment]
50f6d14d8a894494e812a19f6529511e0fd28344 appears to have cut off UBC, which although administratively is outside Vancouver, is part of the city.

**Comment by heffergm** [comment]
Hi Paul,
Our bounding boxes are entirely arbitrary and based on user request. Of you
care to supply a new bbox I'd be happy to merge it.

--
Grant

**Comment by pnorman** [comment]
I [did](https://github.com/mapzen/metroextractor-cities/issues/146#issue-55189946), in this very issue. 

Personally I'd find the box I gave for Metro Vancouver more useful than the one for Vancouver - but which one you want is a policy decision. Either of them is better than the current one.
