### ISSUE TITLE
Sunshine Coast, Australia

### ISSUE THREAD

**Issue by mark31** [mapzen/metroextractor-cities#151]
Would appreciate it if you could add the Sunshine Coast, third largest urban area in the state of Queensland.

 "sunshine_coast_australia": {
"bbox": {
"top": "-26.350",
"left": "152.835",
"bottom": "-27.001",
"right": "153.155"

Thanks

**Comment by heffergm** [comment]
Added here: 5a40dd35c1887d067303cbc207ea9029429aec96
