### ISSUE TITLE
Mosul governorate of iraq

### ISSUE THREAD

**Issue by REACHIraq** [mapzen/metroextractor-cities#157]
Would appreciate it if you could add the Mosul governorate, second largest city of the Iraq

 "mosul_iraq": {
                    "bbox": {
                        "top": "36.5234",
                        "left": "42.8439",
                        "bottom": "36.1684",
                        "right": "43.5079"
                    }

**Comment by heffergm** [comment]
Done: 6d6ab866161fb4d992b24b9278ee588444be4b9b
