### ISSUE TITLE
Pull Request for Liverpool England

### ISSUE THREAD

**Issue by mikeytt** [mapzen/metroextractor-cities#159]
Hello - first time here so hopefully I'm doing this correctly! Can i ask a Pull Request for Liverpool England? Wasn't sure if I should add it to cities.json or not, so didn;t want to do anything wrong! All co-ordinates are correct below. Many thanks.

"liverpool_england": {
"bbox": {
"top": "53.5144",
"left": "-3.2011",
"bottom": "53.2825",
"right": "-2.7404"
}

**Comment by heffergm** [comment]
Added: f1aae24c88399898f710edfdc64b1ca82cc8f69d
