### ISSUE TITLE
city naming convention

### ISSUE THREAD

**Issue by anabellamy** [mapzen/metroextractor-cities#161]
hello! i am using the (fantastic!) cities.json file and noticed that the entry for raleigh (north carolina) does not follow the apparent naming convention which separates city and state/country by underscore, and uses hyphens within the city and state/country parts. thought i would let you know (and not sure if i should have/could have fixed this myself).

i love metroextractor. thanks!

**Comment by heffergm** [comment]
Fixed, thanks.
