### ISSUE TITLE
adding more Iraqi cities

### ISSUE THREAD

**Issue by REACHIraq** [mapzen/metroextractor-cities#162]
Hello,

Would appreciate it if you could add these Iraqi cities.

"zhumar_iraq": {
"bbox": {
"top": "36.673988",
"left": "42.592347",
"bottom": "36.645599",
"right": "42.618839"
}

"tikrit_iraq": {
"bbox": {
"top": "34.688143",
"left": "43.627575",
"bottom": "34.567065",
"right": "43.706397"
}

"ramadi_iraq": {
"bbox": {
"top": "33.440319",
"left": "43.241598",
"bottom": "33.397553",
"right": "43.336926"
}

"jalawla_iraq": {
"bbox": {
"top": "34.294812",
"left": "45.145368",
"bottom": "34.245498",
"right": "45.185842"
}

"Hit_iraq": {
"bbox": {
"top": "33.667770",
"left": "42.787062",
"bottom": "33.616338",
"right": "42.855977"
}

"Haditha_iraq": {
"bbox": {
"top": "34.156549",
"left": "42.347412",
"bottom": "34.075076",
"right": "42.400046"
}

"Baji_iraq": {
"bbox": {
"top": "34.958597",
"left": "43.460272",
"bottom": "34.893591",
"right": "43.520330"
}

**Comment by heffergm** [comment]
Added: https://github.com/mapzen/metroextractor-cities/commits/master

Available next week.
