### ISSUE TITLE
March 14, 2015 update Louisville KY

### ISSUE THREAD

**Issue by schnuerle** [mapzen/metroextractor-cities#180]
Not sure if this is the best place to ask this question, but did last weekend's update work?  We are importing buildings into Louisville, KY and did a lot of data last week.  

Comparing what is in the latest extract with what's in OSM now seems to not include most of our updates.

Extract:
https://s3.amazonaws.com/metro-extracts.mapzen.com/louisville_kentucky.imposm-shapefiles.zip
(louisville_kentucky.osm-buildings.shp)

OSM example area with buildings not in extract:
https://www.openstreetmap.org/#map=16/38.0541/-85.9027 

Thanks, maybe I'm just misunderstanding the process.

**Comment by heffergm** [comment]
I'm not entirely sure the buildings you're looking for are actually buildings. Looks like the cement plant is actually a combination of ways, which in the case of a bounding box at the edge of a river would result in it potentially not being part of the extract. Unfortunately the only way we can derive extracts is by severing dangling ways to avoid resource constraints. I'll look into it a bit more, but my suspicion is this is the result of the data being at the edge of the extract boundary.

**Comment by schnuerle** [comment]
Thanks a lot for checking. That's just an example area - should be thousands more across the city that aren't here. Most of those houses are marked with building:yes and aren't showing up. Red and green areas in this job show where buildings should be. http://tasks.openstreetmap.us/job/50

**Comment by heffergm** [comment]
Ok, so I'm a little confused now. Have all your missing buildings been successfully imported into OSM already or no?

If so, then they should appear in our extracts when a full OSM planet containing all your data is released. All our extracts are built against the planet osm pbf, the last of which was delivered on March 11th. If your data was ingested after that, it definitely won't be in our extracts yet.

**Comment by schnuerle** [comment]
That's it then. They are in OSM now. I didn't know it was based on the global planet pbf date. I thought it was based on the March 14 mapzen extract date. We did do a lot March 11-13. You can close this and sorry I didn't come across the right info.

**Comment by heffergm** [comment]
I see. Yeah, the mapzen extract data on the page is just the last date we generated data from the planet, but the planet data itself is dependent on whenever it's released by OSM. 

I'll see about adding some information to clarify.
