### ISSUE TITLE
Beauvais, France

### ISSUE THREAD

**Issue by eileentalley** [mapzen/metroextractor-cities#181]
Hi everybody!
For a work I have to do for tomorrow, I would need to add the town of Beauvais, in France.
The coordinates are:

Top: 49.470
left: 2.014
bottom: 49.399
right: 2.173

I've tried to add it myself, but don't know if I did it right..?

Thank you!

**Comment by heffergm** [comment]
Hello,
We generate extracts weekly from OSM planet data, so I wouldn't be able to provide something for you tomorrow.

If you think you'll still need the extract let me know and I'll add your bounding box.

**Comment by eileentalley** [comment]
ok I understand!Yes please add it still!Thank you so much,
Eileen

Date: Mon, 16 Mar 2015 09:30:49 -0700

**Comment by heffergm** [comment]
All set: 9a819c169cbe60294a16b701346d65246ca4e019
