### ISSUE TITLE
san luis obispo

### ISSUE THREAD

**Issue by chadbunn** [mapzen/metroextractor-cities#184]

**Comment by heffergm** [comment]
Hi,
Could you clarify for me which particular San Luis Obispo you're looking to add? Turns out there are quite a few around the world.

**Comment by chadbunn** [comment]
My bad, I was looking for the City of San Luis Obispo, CA, USA

**Comment by heffergm** [comment]
373112b1630ddd12a45b4c75670cf58ec4c7113e
