### ISSUE TITLE
City Boundaries

### ISSUE THREAD

**Issue by thomasjfox1** [mapzen/metroextractor-cities#187]
Would it be possible to include the city boundary data for each city included in the extracts? Some have the data and some don't. For example the city of Rome has admin data on multiple areas such as Vatican City, but doesn't actually include data on the the edges of the city of Rome itself. It would be great if this could be included. Thanks!

**Comment by heffergm** [comment]
Unfortunately because our extracts are of arbitrary size this isn't possible to do uniformly. We are working on another project that will deal solely with exposing administration boundaries data, so keep an eye out for that in the near future.
