### ISSUE TITLE
Malmö, Sweden

### ISSUE THREAD

**Issue by rotsee** [mapzen/metroextractor-cities#190]
Malmö, the third biggest city of Sweden. 

"Malmo_sweden": {
"bbox": {
"top": "55.68",
"left": "12.715",
"bottom": "55.485",
"right": "13.167"
}

**Comment by heffergm** [comment]
be02e6cfc754cb00197157411f0a2edef59a4781

**Comment by rotsee** [comment]
Wow, that was quick! Thanks!
