### ISSUE TITLE
Kochi , India

### ISSUE THREAD

**Issue by sarfraznawaz001** [mapzen/metroextractor-cities#195]
Can you please include Kochi , India

"Kochi": {
"bbox": {
"top": "10.0906",
"left": "76.1703",
"bottom": "9.7847",
"right": "76.3893"
}

**Comment by KathleenLD** [comment]
Thank you for providing the json for Kochi! I've added it to the metro extracts (https://mapzen.com/metro-extracts/) and you should be able to download it after this weekend.
