### ISSUE TITLE
Tamale, Ghana

### ISSUE THREAD

**Issue by emmanosh5491** [mapzen/metroextractor-cities#197]
hi,
In a developing country like Ghana in West Africa, Tamale is a city that is rapidly growing and should be listed as part of the cities with extracts. Several developments initiatives have been going on there in the past 10 years and is worth adding its shapefiles to your data base.

There is more about Tamale here http://en.wikipedia.org/wiki/Tamale,_Ghana

**Comment by KathleenLD** [comment]
Thanks for suggesting this! I've just added Tamale, and you should be able to see the extract available on https://mapzen.com/metro-extracts/ after the weekend (when all extracts are cut).
