### ISSUE TITLE
Barnstable, MA

### ISSUE THREAD

**Issue by sgoulet** [mapzen/metroextractor-cities#199]
Could you please add:

 "barnstable_massachusetts": {
                    "bbox": {
                        "top": "41.739181",
                        "left": "-70.382270",
                        "bottom": "41.608130",
                        "right": "-70.216603"
                    }
                },

Thank you!

**Comment by KathleenLD** [comment]
@sgoulet thank you for providing the json! You'll be able to see Barnstable on the Metro Extracts site next time they are run (over the weekend).

**Comment by sgoulet** [comment]
Thank you @KathleenLD!
