### ISSUE TITLE
Please add Pisa, Italy

### ISSUE THREAD

**Issue by kkporter** [mapzen/metroextractor-cities#201]
Please add Pisa, Italy
Many thanks!

"Pisa_Italy": {
"bbox": {
"top": "43.737145",
"left": "10.355810",
"bottom": "43.670133",
"right": "10.443701"
}

**Comment by KathleenLD** [comment]
@kkporter thanks for providing this json! I've added Pisa in #226 and you'll be able to access the extract after this weekend when they are next updated.
