### ISSUE TITLE
Please add Rouen?

### ISSUE THREAD

**Issue by eileentalley** [mapzen/metroextractor-cities#204]
Hi! I tried to add Rouen on the 14th of april, dont know why it isn't on mapzen?

Is it possible to add it?

The coordinates are: 
top: 49.4942
left: 1.0245
down: 49.3647
right: 1.2583

Thank you soo much!!!

Have a great day!

**Comment by eileentalley** [comment]
When is the next update please?

Thanks!

Eileen

**Comment by KathleenLD** [comment]
@eileentalley thank you so much for providing these coordinates! I've added Rouen in #226 and you'll be able to get the extract after this weekend when they next update.

**Comment by eileentalley** [comment]
Thank you!!!! :)
