### ISSUE TITLE
City to add: Fallujah, Iraq

### ISSUE THREAD

**Issue by REACHIraq** [mapzen/metroextractor-cities#211]
Would appreciate it if you could add Fallujah city.

"Fallujah_Iraq": {
"bbox": {
"top": "33.4859",
"left": "43.5217",
"bottom": "33.2456",
"right": "44.0126"
}

**Comment by KathleenLD** [comment]
@REACHIraq thanks for providing the json! I've added that into `master` in #228. You'll be able to download the extract after this weekend when the project updates.
