### ISSUE TITLE
Changes to Cairns, Australia

### ISSUE THREAD

**Issue by mark31** [mapzen/metroextractor-cities#212]
The following bounding box would better capture the urban area of Cairns. The current bounding box goes too far to the E and W, and not far enough to the N and S. Thanks!

                "cairns_australia": {
                    "bbox": {
                        "top": "-16.732",
                        "left": "145.606",
                        "bottom": "-17.131",
                        "right": "145.838"

**Comment by KathleenLD** [comment]
@mark31 Thanks for the edit! I've added that into `master`. You'll be able to grab the updated extract after this weekend when they are all updated
