### ISSUE TITLE
Please add Metz?

### ISSUE THREAD

**Issue by eileentalley** [mapzen/metroextractor-cities#217]
Hello!
How are you?
Is it possible to add the city of Metz in France? 
The coordinates are:

top: 49.1590
left: 6.0559
down: 49.0534
right: 6.3491

Thank you so very much!

Eileen

**Comment by KathleenLD** [comment]
Hi again @eileentalley! Thanks for the coordinates for Metz! I've added it in #226 and you'll be able to get the extract after they all update this weekend.
