### ISSUE TITLE
Support for Philippine Cities

### ISSUE THREAD

**Issue by eflegara** [mapzen/metroextractor-cities#231]
First off, such awesome work you have here. May I request adding the following Philippine cities?

- [Cebu City, Philippines] (https://www.openstreetmap.org/search?query=Cebu%20City#map=12/10.3167/123.8907)
- [Davao City, Philippines] (https://www.openstreetmap.org/search?query=Davao%20City#map=12/7.0731/125.6128)
- [Cagayan de Oro City, Philippines] (https://www.openstreetmap.org/search?query=Cagayan%20de%20Oro#map=12/8.4822/124.6472)

Thank you again!

**Comment by KathleenLD** [comment]
Hi @eflegara! I've added the cities you suggested. You'll be able to access the extracts after this weekend.

**Comment by eflegara** [comment]
Thank you, @KathleenLD! Very much appreciate this!
