### ISSUE TITLE
Please add Brighton, England

### ISSUE THREAD

**Issue by kkporter** [mapzen/metroextractor-cities#245]
Please add Brighton, England
Many thanks!

"Brighton, England": {
"bbox": {
"top": "50.882767",
"left": " -0.251329",
"bottom": "50.775207",
"right": "-0.047396"
}

**Comment by KathleenLD** [comment]
@kkporter thanks for including these coordinates! I've added Brighton and merged it into `master` in #255. You should be able to access the extract after this weekend.
