### ISSUE TITLE
City to add: Sana'a, Yemen

### ISSUE THREAD

**Issue by nassosstylianou** [mapzen/metroextractor-cities#248]
Would it be possible to add Sana'a, in Yemen?
Thank you very much.

"Sana'a_Yemen": {
"bbox": {
"top": "15.5337",
"left": "43.9384",
"bottom": "15.1517",
"right": "44.4624"
}

**Comment by KathleenLD** [comment]
@nassosstylianou thanks for providing these coordinates! I've added Sana'a into `master` and you'll be able to get this extract after the weekend.
