### ISSUE TITLE
City to add: Nicosia, Cyprus

### ISSUE THREAD

**Issue by nassosstylianou** [mapzen/metroextractor-cities#249]
Would it be possible to add Nicosia, Cyprus?
Thanks.

"Nicosia, Cyprus": {
"bbox": {
"top": "35.2145",
"left": "33.2285",
"bottom": "35.0648",
"right": "33.4904"
}

**Comment by KathleenLD** [comment]
@nassosstylianou thanks for providing these coordinates as well! I've also added Nicosia.

**Comment by nassosstylianou** [comment]
:+1: brilliant, thanks so much
