### ISSUE TITLE
Please create extract of St. Lucia

### ISSUE THREAD

**Issue by geomantic** [mapzen/metroextractor-cities#251]
Hi, 
Requesting an extract of the island nation of St. Lucia, please. It's roughly the same area as Toronto, but not nearly as dense, so I think it should not be too unwieldy. Thanks!

**Comment by KathleenLD** [comment]
@geomantic ask and ye shall receive. 

I've added this in ba8c808 so it'll be in the next PR into `master` . You should be able to access the extract after this weekend!
