### ISSUE TITLE
City to add: Teresina, Brazil

### ISSUE THREAD

**Issue by regispires** [mapzen/metroextractor-cities#254]
Please, I would like to ask you to add Teresina, Brazil:

"teresina_brazil": {
"bbox": {
"top": "-4.787",
"left": "-42.970",
"bottom": "-5.586",
"right": "-42.599"
}
}

**Comment by KathleenLD** [comment]
@regispires thanks for providing these coordinates! I've added Teresina into `master` and you'll be able to get this extract after the weekend.
