### ISSUE TITLE
City to add: Guangzhou, China

### ISSUE THREAD

**Issue by LeslieFire** [mapzen/metroextractor-cities#259]
Please, I would like to ask you to add Guangzhou, China:

"guangzhou_china": {
        "bbox": {
                "top": "23.9812",
                "left": "112.1814",
                "bottom": "22.5329",
                "right": "114.9719"
        }
}

**Comment by KathleenLD** [comment]
@LeslieFire thanks for providing these coordinates! I've added Guangzhou into `master` and you'll be able to get this extract after the weekend.
