### ISSUE TITLE
City to add: Shangrao, China

### ISSUE THREAD

**Issue by hanchao** [mapzen/metroextractor-cities#262]
Please, I would like to ask you to add Shangrao, China:

"shangrao_china": {
"bbox": {
"top": "28.5526",
"left": "117.8201",
"bottom": "28.3467",
"right": "118.0817"
}
}

**Comment by KathleenLD** [comment]
@hanchao thanks for providing these coordinates! I've added Shangrao into `master` and you'll be able to get this extract after the weekend.
