### ISSUE TITLE
Please add Tianjing, China

### ISSUE THREAD

**Issue by kkporter** [mapzen/metroextractor-cities#270]
Please add Tianjing, China
Many thanks!

"Tianjing, China": {
"bbox": {
"top": "39.779378",
"left": "116.527571",
"bottom": "38.377693",
"right": "118.530661"
}

**Comment by Ren-Chang** [comment]
Hi, @KathleenLD 
I'm commenting this closed issue just to tell you that this newly added Chinese city is not correctly spelled. The correct name should be 'Tianjin', without the ending 'g'. c.f. https://en.wikipedia.org/wiki/Tianjin

**Comment by KathleenLD** [comment]
@Ren-Chang Thank you for catching that! I've made the fix and you'll see it updated after this weekend.
