### ISSUE TITLE
OSM Map/Shapefile of Washington DC

### ISSUE THREAD

**Issue by gharabed** [mapzen/metroextractor-cities#274]
I am looking for an OSM map/shapefile for metro Washington DC.

**Comment by KathleenLD** [comment]
@gharabed if you search for "DC" or "Baltimore" in the [Metro Extracts site](https://mapzen.com/data/metro-extracts/) you'll get the entire Washington - Baltimore metro area. 

We should probably adjust the name to make it easier to find though, so thanks for bringing it up!
