### ISSUE TITLE
Please add Wieluń, Poland

### ISSUE THREAD

**Issue by matkoniecz** [mapzen/metroextractor-cities#276]
from http://www.openstreetmap.org/?mlat=51.2869&mlon=18.4436#map=12/51.2869/18.4436
to http://www.openstreetmap.org/?mlat=51.1407&mlon=18.7035#map=12/51.1407/18.7035

This place is one of the best mapped towns in Poland and a good testing location.

**Comment by KathleenLD** [comment]
@matkoniecz I've added Wieluń and you'll be able to access the extract after this weekend. Thanks!

**Comment by matkoniecz** [comment]
Thanks!
