### ISSUE TITLE
Please add Annecy, France

### ISSUE THREAD

**Issue by i20s** [mapzen/metroextractor-cities#277]
I tried to run the test, but i didn't succeed to run it.
Thank you for the add :)

"annecy_france": {
                    "bbox": {
                        "top": "46.026",
                        "left": "5.998",
                        "bottom": "45.765",
                        "right": "6.298"
                    }

**Comment by KathleenLD** [comment]
@i20s thanks for providing this JSON. I've added it into `master` and you'll be able to access the extract after this weekend.
