### ISSUE TITLE
Please add Palm Beach County, Fla.

### ISSUE THREAD

**Issue by stucka** [mapzen/metroextractor-cities#288]
I think I've got this right:
                "palm-beach-county_florida": {
                    "bbox": {
                        "top": "26.9709",
                        "left": "-80.8862",
                        "bottom": "26.3208",
                        "right": "-79.9743"
                    }
                },

(Whitespace is correct in raw version)

**Comment by KathleenLD** [comment]
@stucka thanks for these coordinates! I've added this in f151bf5 and you'll be able to download the extract after this weekend.
