### ISSUE TITLE
Please Add Shijizhuang, China

### ISSUE THREAD

**Issue by youngjiggi** [mapzen/metroextractor-cities#290]
"shijiazhuang_china": {
"bbox": {
"top": "38.010",
"left": "114.446",
"bottom": "37.993",
"right": "114.463"
}
}

**Comment by KathleenLD** [comment]
@youngjiggi thanks for this JSON! I've added added this in c7b3191 and you'll be able to download the extract after this weekend.

**Comment by youngjiggi** [comment]
Thank you Kathleen Again. That's great. I don't see it on the website yet but maybe I will soon!
https://mapzen.com/data/metro-extracts

**Comment by KathleenLD** [comment]
@youngjiggi hm, you're right. Thanks for mentioning it! It looks as though the updates didn't run over the weekend. I'm looking into this!

**Comment by KathleenLD** [comment]
@youngjiggi you should be able to access the extract now. Thanks again!
