### ISSUE TITLE
Please Update Sapporo, Japan

### ISSUE THREAD

**Issue by kkporter** [mapzen/metroextractor-cities#298]
Please Update Sapporo, Japan
Many thanks!

"Nara, Japan": {
"bbox": {
"top": "43.302253",
"left": "140.488001",
"bottom": "42.651186",
"right": "141.920925"
}

**Comment by KathleenLD** [comment]
@kkporter I'm not clear on what you're asking for here-- are you looking for updates to Sapporo or to Nara?

**Comment by kkporter** [comment]
sorry it should be sapporo

"Sapporo, Japan": {
"bbox": {
"top": "43.302253",
"left": "140.488001",
"bottom": "42.651186",
"right": "141.920925"
}

**Comment by KathleenLD** [comment]
@kkporter thanks for clarifying. I've updated Sapporo and you'll be able to access the updated extract after this weekend.
