### ISSUE TITLE
Boston metro area cuts off northern portion

### ISSUE THREAD

**Issue by awbirdsall** [mapzen/metroextractor-cities#314]
To my eye, the northern boundary of the `boston_massachusetts` region of 42.399 N is not far enough north, and cuts off part of the Boston metro area. For example, I was messing around with mapping the stations of the local bike sharing system, and the stations extend as far north as 42.404 N.

I think the boundary should at least extend to the northernmost border of Somerville, MA, at 42.417 N. Another idea would be to extend the northern boundary so that the northern and southern boundaries are about symmetrical from "downtown Boston" at around 42.360 N, putting the northern boundary at 42.492 N. I'm not very familiar with the Boston area, so any competing suggestions would be welcome!

**Comment by KathleenLD** [comment]
@awbirdsall Thanks for catching this! I made this adjusgement in dd9a14d and you'll be able to access the updated extract after this weekend.

**Comment by awbirdsall** [comment]
Great, thanks!
