### ISSUE TITLE
Add more cities in Ireland

### ISSUE THREAD

**Issue by nvkelso** [mapzen/metroextractor-cities#319]
From an inquiry to hello@mapzen.com, more cities in Ireland are requested.

Proposed:
- [x] Cork
- [x] Limerick
- [x] Galway
- [x] Waterford (from @nvkelso to round out the major set)

Current cities:
<img width="335" alt="screen shot 2015-10-13 at 09 10 09" src="https://cloud.githubusercontent.com/assets/853051/10458931/7570f50a-718a-11e5-9db8-a6b89093df42.png">

**Comment by KathleenLD** [comment]
Done! 

Sorry for the delay, @nvkelso!
