### ISSUE TITLE
Map of Vienna

### ISSUE THREAD

**Issue by alam4699** [mapzen/metroextractor-cities#320]
To Whom it May Concern, 

I was wondering if I could request a dataset of Vienna, Austria. I saw that you had Bratislava, but it is not what I am looking for. 

![outline_vienna](https://cloud.githubusercontent.com/assets/15153684/10535782/51b93280-73ab-11e5-8562-96d3ad26f071.jpg)

**Comment by KathleenLD** [comment]
@alam4699 thanks for noting this-- I've split Vienna from Bratislava and they are now two distinct extracts. You'll be able to access them after this weekend.
