### ISSUE TITLE
Map of Cameroon AFRICA

### ISSUE THREAD

**Issue by chriswacta** [mapzen/metroextractor-cities#324]
Map of Cameroon AFRICA

**Comment by KathleenLD** [comment]
@chriswacta is there a specific city in Cameroon you were looking for? Otherwise you might want to look at the Geofabrik country extracts: http://download.geofabrik.de/africa/cameroon.html

**Comment by chriswacta** [comment]
Thank you for your answer.
I was looking for any city...
Thank yiu
