### ISSUE TITLE
city to add: Tours, France

### ISSUE THREAD

**Issue by Cyrille37** [mapzen/metroextractor-cities#334]
Hi,
Could you please add "Tour(s)plus", the villages agglomeration around Tours.
The relation is: http://www.openstreetmap.org/relation/1663056

Or if you do not want villages agglomeration, the Tours city is:
http://www.openstreetmap.org/relation/76306#map=13/47.3943/0.6951

Thanks a lot
Cyrille.

**Comment by KathleenLD** [comment]
@Cyrille37 I've added Tours and the surrounding area into master. You'll be able to access the extract after this weekend.

**Comment by Cyrille37** [comment]
Thanks a lot !!
Cheers, Cyrille.
