### ISSUE TITLE
Add support for Albanina cities

### ISSUE THREAD

**Issue by diskmanti** [mapzen/metroextractor-cities#353]
I would like to have the possibility to use metroextractor-cities for Albanina cities if it is possible.

**Comment by KathleenLD** [comment]
@diskmanti which cities in particular are you looking for?

**Comment by diskmanti** [comment]
I am interested in Tirana, Albania, since I live and work here.

**Comment by KathleenLD** [comment]
@diskmanti Ok, cool. I've added Tirana and you should be able to access the extract after this weekend.

**Comment by diskmanti** [comment]
Thank you very much!!! I can't wait to see how It will look.
