### ISSUE TITLE
Please Add: Maiduguri, Nigeria

### ISSUE THREAD

**Issue by noahgarfinkle** [mapzen/metroextractor-cities#358]
Hello, could I please request the addition of Maiduguri, Nigeria?  I apologize, I am new to GIT and am struggling to push the change myself (403 error).  Thank you for your time!
		"maiduguri_nigeria": {
                    "bbox": {
                        "top": "12.142",
                        "left": "12.12.679",
                        "bottom": "11.553",
                        "right": "13.526"
                    }
                },

**Comment by KathleenLD** [comment]
@noahgarfinkle thanks for providing these coordinate! I've added Maiduguri and you'll be able to access the extract after this weekend.
