### ISSUE TITLE
Please add Townsville, Queensland, Australia

### ISSUE THREAD

**Issue by brownidj** [mapzen/metroextractor-cities#359]
Please add Townsville, Queensland, Australia

**Comment by KathleenLD** [comment]
@brownidj I've added Townsville to `master`. You'll be able to access the extract after this weekend.

**Comment by brownidj** [comment]
Many thanks, much appreciated. Was it a lot of work? Can I get involved and help out?

David

**Comment by KathleenLD** [comment]
@brownidj 

Hi David, thanks for asking! It's definitely not a ton of work. You can see all that I added to `cities.json` here: 30481e6

If you like, when you see other cities that need to be added you can submit a Pull Request to this repo where you edit `cities.json` in the same way. I'll review and merge them in. For finding bounding boxes, I like to use this tool: http://boundingbox.klokantech.com/. 

I'm happy to help if you've got questions!
