### ISSUE TITLE
about how to handle umlauts in town names

### ISSUE THREAD

**Issue by benediktg** [mapzen/metroextractor-cities#376]
Should (German) town names in the `cities.json` file be written with umlauts or with their appropriate replacement variant?

As an example: Would `"würzburg_germany"` or `"wuerzburg_germany"` be correct?

**Comment by KathleenLD** [comment]
@migurski @baldur any thoughts on this?

**Comment by mcl33** [comment]
For people without umlauts on their keyboard it's hard to access those cities when searching on mapzen, isn't it?

**Comment by louh** [comment]
@KathleenLD When we were doing the OpenVenues site, we were generating an additional manifest file that would then be matched up with the S3 bucket's file list. The second manifest contained additional metadata to help display names better. This way we could keep file names simple but still have some place to store information about what a display name should look like. I didn't personally like having to merge two manifests during the site build time, but it did the job.

For searching, we should [deburr](https://lodash.com/docs#deburr) the search inputs and region names and this will make it moot whether people type umlauts or not.
