### ISSUE TITLE
Hellertown, Pennsylvania

### ISSUE THREAD

**Issue by sutherland1679** [mapzen/metroextractor-cities#379]
If you could add Hellertown, Pennsylvania I would really appreciate it for a local project I am doing. Thank you!

Top left corner 40.597693, -75.368183
Bottom right corner 40.560470, -75.317972

**Comment by KathleenLD** [comment]
@sutherland1679 thanks for this suggestion. @benediktg has added Hellertown and I've just merged into  `master`. You'll be able to access the extract after this weekend.
