### ISSUE TITLE
add the following cities please

### ISSUE THREAD

**Issue by mcl33** [mapzen/metroextractor-cities#388]
Hi,
I'm doing a project with OSM and tried to get the (supposedly) 20 largest cities from each continent.
The following were missing, maybe you can add them?

Africa:
- [x] Ekurhuleni, South Africa
- [x] Giza, Egypt
- [x] Ibadan, Nigeria

Asia:
- [x] Shenzhen, China
- [x] Dongguan, China
- [x] Nanjing, China
- [x] Shenyang, China
- [x] Ningbo, China

Europe
/

North America:
- [x] Exatepec de Morelos, Mexico
- [x] Juaréz, Mexico
- [x] Tijuana, Mexico (separate from San Diego)
- [x] San Diego, Mexico (separate from Tijuana)
- [x] Leon, Mexico

South America:
- [x] Cali, Colombia
- [x] Manaus, Brazil
- [ ] Maracaibo, Brazil

Also, I was hoping to get the Top 20 German Cities; a few are missing:
- [x] Dortmund
- [x] Essen
- [x] Hanover
- [x] Bochum
- [x] Bielefeld
- [x] Bonn
- [x] Münster

Let me know if it would be better to open separate issues for that.
Thanks, Michael

**Comment by mcl33** [comment]
Thanks for the help so far, appreciate your work!

**Comment by KathleenLD** [comment]
@mcl33 did you mean Maracaibo, Venezuela? That city looks larger than Maracaibo, Brazil.

**Comment by mcl33** [comment]
@KathleenLD You're totally right its Maracaibo, Venezuela. Thank you so much for the work!

**Comment by KathleenLD** [comment]
@mcl33 these have all been merged in. You'll be able to access the extracts after this weekend.

**Comment by mcl33** [comment]
@KathleenLD I just noticed, that münster is speeld with _ü_, while for example Düsseldorf is spelled with _ue_. Not sure about the convention regarding this.
