### ISSUE TITLE
Poland - Lodz

### ISSUE THREAD

**Issue by Houmr9** [mapzen/metroextractor-cities#389]
Hello,

can I have a request to add city of Lodz in Poland please?

"lodz_poland": {
                    "bbox": {
                        "top": "51.869",
                        "left": "19.252",
                        "bottom": "51.676",
                        "right": "19.708"
                    }
                },

Thanks

**Comment by KathleenLD** [comment]
@Houmr9 thanks for these coordinates! I'm adding Lodz in ecc2452 and it will be merged into `master` so that you can access the extract by next week.

**Comment by Houmr9** [comment]
thank you
