### ISSUE TITLE
Mashhad, Iran

### ISSUE THREAD

**Issue by saeedghazijoolaee** [mapzen/metroextractor-cities#390]
Mashhad is second largest city of Iran and capital of Razavi Khorasan, one of greatest provinces of Iran.

**Comment by KathleenLD** [comment]
@saeedghazijoolaee thanks for this suggestion. I've added Mashhad in a1bbaed and you'll be able to access the extract after this coming weekend.

**Comment by saeedghazijoolaee** [comment]
Hi,
Thanks For your kind attention.
With best wishes Monday, 01 February 2016, 05:49PM +0330 from Kathleen Danielson < notifications@github.com> :
