### ISSUE TITLE
Camino de Santiago, Spain

### ISSUE THREAD

**Issue by Sofie1608** [mapzen/metroextractor-cities#392]

**Comment by KathleenLD** [comment]
@Sofie1608 can you be more specific about the metro area you're looking for? Wikipedia lists [Camino de Santiago](https://en.wikipedia.org/wiki/Camino_de_Santiago) as any of a variety of pilgrimage routes.

**Comment by Sofie1608** [comment]
@KathleenLD , Yes, I meant to write Santiago de Campostella, especially the area around the cathederal.

**Comment by Sofie1608** [comment]
@KathleenLD I am very new to this site! Looked at Mapzen to find the data in order to look at the map in the program QGIS. Do you have any idea how I can get this data? Thanks for help!

**Comment by KathleenLD** [comment]
@Sofie1608 this blog post might have the information you're looking for: https://mapzen.com/blog/use-metro-extracts-in-qgis

**Comment by KathleenLD** [comment]
@Sofie1608 I've added Santiago de Campostela-- you'll be able to access the extract after this weekend.

**Comment by Sofie1608** [comment]
@KathleenLD Thank you so much for your help!:)
