### ISSUE TITLE
Add cities from Guatemala

### ISSUE THREAD

**Issue by juanmedrano** [mapzen/metroextractor-cities#395]
Hi,

First of all, thanks all your help. I am not totally sure about how to make the request, so I will write here the names of the departments (or states) from Guatemala and the respective needed cities.

If there is anything I can do to make the work easier please let me know. Basically I need the cities of the country of Guatemala, but I think the listed down below are the ones I will use for right now. If the list is too large please let me know, and I will reduce it to the limit you propose. Thank your so much for your support.

The cities I would like to request are, all of them from Guatemala (Country):

Petén
- Dolores
- Melchor de Mencos
- San Francisco
- Sayaxché
- Flores
- Poptún
- San José
- La Libertad
- San Andrés
- San Luis
- Las Cruces
- San Benito
- Santa Ana

Alta Verapaz
- Chahal
- Lanquín
- San Juan Chamelco
- Santa María Cahabón
- Tucurú
- Chisec
- Panzós
- San Pedro Carchá
- Senahú
- Cobán
- Raxruhá
- Santa Catalina La Tinta
- Tactic
- Fray Bartolomé de las Casas
- San Cristóbal Verapaz
- Santa Cruz Verapaz
- Tamahú

Baja Verapaz
- Cubulco
- Salamá
- Granados
- San Jerónimo
- Purulhá
- San Miguel Chicaj
- Rabinal
- Santa Cruz el Chol

Izabal
- El Estor
- Puerto Barrios
- Livingston
- Los Amates
- Morales

Municipios de Quiché
- Canillá
- Chichicastenango
- Joyabaj
- Sacapulas
- San Juan Cotzal
- Zacualpa
- Chajul
- Chinique
- Nebaj
- San Andrés Sajcabajá
- San Pedro Jocopilas
- Chicamán
- Cunén
- Pachalum
- San Antonio Ilotenango
- Santa Cruz del Quiché
- Chiché
- Ixcán
- Patzité
- San Bartolomé Jocotenango
- Uspantán

**Comment by jaraddlfisher** [comment]
I would be interested in doing this but this would forsure take some time and feel it would be fair to ask for some kind of compensation.

**Comment by IndyHurt** [comment]
@juanmedrano do you have bounding box coordinates for these cities?  That would be very helpful.  
Here is an example:

"guadalajara_jalisco_mexico": {
                    "bbox": {
                        "top": "20.840",
                        "left": "-103.508",
                        "bottom": "20.440",
                        "right": "-103.153"
                    }
                },

**Comment by juanmedrano** [comment]
@jaraddlfisher Thanks for your offer and for sure it would be fair. Should I reply back via email? 

@IndyHurt  Thanks for the suggestion. Right now I don't have them, but I could get them and then fork and make a pull request in the "cities" document right?

**Comment by jaraddlfisher** [comment]
@juanmedrano
Send me email to Jaradd.fisher@gmail.com

**Comment by KathleenLD** [comment]
@IndyHurt and I have just added in the cities from Petén. You can see them in #401. Those extracts will be available after this coming weekend, but the others are still outstanding.

**Comment by KathleenLD** [comment]
@juanmedrano because of the number of cities requested compared to the relative size of Guatemala, I think that you'd be better served working with the Country Extracts from Geofabrik: http://download.geofabrik.de/central-america/guatemala.html

I'm going to close this issue now, but if you find that you need a specific metro region feel free to open a new issue.

**Comment by jaraddlfisher** [comment]
@juanmedrano 
Still interested in doing this..
Email me..
Jaraddl.fisher@gmail.com
