### ISSUE TITLE
Add kingdom of Bahrain (Asia/Middle East)

### ISSUE THREAD

**Issue by stone2191** [mapzen/metroextractor-cities#399]
I would like kingdom of Bahrain added as a city. Bahrain is a very small Island in the middle east, it barely can be seen on the world street map. The Capital of Bahrain is Manama.

Bounding Box:
NE 26.292391, 50.828499
SW 25.5422, 50.385799

**Comment by KathleenLD** [comment]
@stone2191 thanks for these coordinates! I've added Bahrain and you'll be able to access the metro extract after this weekend.

**Comment by stone2191** [comment]
awesome, thanks.
