### ISSUE TITLE
Add new city - Valdivia Chile

### ISSUE THREAD

**Issue by ovargasmaqueda** [mapzen/metroextractor-cities#408]
Hello!

First at all, I would like to thank you for this tool, it is really useful for the world comunity.

I am posting today to ask if it is possible to add a new city, Valdivia (Chile).
The coordinates are:
Latitude top: -39.687633
Latitude bottom: -39.982466
Longitude right:-73.072054
Longitude left: -73.500861

Thanks for your support.
Kind regards

**Comment by KathleenLD** [comment]
@ovargasmaqueda thanks for these coordinates! I've added this into `master` and you'll be able to access this extract after this coming weekend.
