### ISSUE TITLE
new city for open street maps

### ISSUE THREAD

**Issue by mtsalomao** [mapzen/metroextractor-cities#410]
Hello,
Thank you for all the useful information. I am working in a Mexican town called Ébano, located in the state of San Luis Potosí. I have the shapefiles of the streets and other features like water bodies that I can share with you, but I was wondering if you could add Ébano to the list and create the building footprint and the land use of the town it would be really helpful for my project.

[ébano_mx.zip](https://github.com/mapzen/metroextractor-cities/files/147101/ebano_mx.zip)
These are the files I have that can also be added, they were taken from INEGI (Instituto Nacional de Estadística y Geografía - México)

Thank you,
Mariana

**Comment by KathleenLD** [comment]
@mtsalomao hi! This repository is actually specifically for pulling data *out* of OSM, not adding data in. 

If we were to create an extract of Ébano you would have access to just the data that is currently in the OSM database (to get a sense of what that is, [take a look at the map](http://www.openstreetmap.org/node/296381616#map=14/22.2230/-98.3622). You'd be able to access a shapefile of the data that's already in OSM, but it sounds like you might already have that. 

Are you familiar with how to manually add data into OSM? There's also [a process for importing data](http://wiki.openstreetmap.org/wiki/Import/Guidelines), but it can be rather complicated. 

I hope this answers your question, but feel free to re-open this issue if I've misunderstood you.
