### ISSUE TITLE
Add new city - Talca Chile

### ISSUE THREAD

**Issue by ovargasmaqueda** [mapzen/metroextractor-cities#417]
Hello.

I'd like to know if it is possible too add a new city, Talca (Chile).

The coordinates are:
Latitude top: -35.334090
Latitude bottom: -35.572317
Longitude right:-71.488069
Longitude left: -71.829995

Thanks for your support.
Kind regards

**Comment by KathleenLD** [comment]
@ovargasmaqueda thanks for these coordinates! I've added Talca and you'll be able to access the extract after this weekend.
