### ISSUE TITLE
Add new city - Rancagua Chile

### ISSUE THREAD

**Issue by ovargasmaqueda** [mapzen/metroextractor-cities#433]
Hello.

I'd like to know if it is possible too add a new city, Rancagua (Chile).

The coordinates are:
Latitude top: -34.051945
Latitude bottom: -34.267508
Longitude right:-70.493950
Longitude left: -70.870437

Thanks for your support.
Kind regards

**Comment by KathleenLD** [comment]
@ovargasmaqueda thanks for these coordinates! I've added Rancagua and you'll be able to access the extract after this coming weekend.
