### ISSUE TITLE
Adding a new city - Iquique Chile

### ISSUE THREAD

**Issue by ovargasmaqueda** [mapzen/metroextractor-cities#437]
Hello.

I'd like to know if it is possible too add a new city, Iquique(Chile).

The coordinates are:
Latitude top: -20.162427
Latitude bottom: -20.336740
Longitude right:-69.996266
Longitude left: -70.209245

Thanks for your support.
Kind regards

**Comment by IndyHurt** [comment]
Hello @ovargasmaqueda !
Here you go: https://mapzen.com/data/metro-extracts/#iquique-chile
