### ISSUE TITLE
extract for Portland, Oregon contains data outside of bounding box

### ISSUE THREAD

**Issue by dobratzp** [mapzen/metroextractor-cities#438]
I'm looking at the extract for Portland, Oregon and it looks like there is some data which doesn't belong.

portland_oregon.osm, line 19849425:
```xml
<way id="404118908" version="1" timestamp="2016-03-16T18:44:38Z" changeset="37879771" uid="2607707" user="Marcos Medeiros">
<nd ref="4063882877"/>
<tag k="name" v="Auto Elétrica Ituiutaba"/>
<tag k="shop" v="car_repair"/>
<tag k="phone" v="+55 34 3268-1246"/>
<tag k="building" v="yes"/>
</way>
```

The Portland extract has only one Node referenced from this Way, and that Node 4063882877 is not in the extract file.

[OSM Way 404118908](http://www.openstreetmap.org/way/404118908) is actually a closed Way object with 5 nodes denoting a car repair shop in Brazil.  Here's what is looks like from the OSM API (still at version 1):

```xml
<way id="404118908" visible="true" version="1" changeset="37879771" timestamp="2016-03-16T18:44:38Z" user="Marcos Medeiros" uid="2607707">
<nd ref="4063882880"/>
<nd ref="4063882878"/>
<nd ref="4063882874"/>
<nd ref="4063882871"/>
<nd ref="4063882877"/>
<nd ref="4063882880"/>
<tag k="building" v="yes"/>
<tag k="name" v="Auto Elétrica Ituiutaba"/>
<tag k="phone" v="+55 34 3268-1246"/>
<tag k="shop" v="car_repair"/>
</way>
```

Neither this Way, nor any of the referenced Nodes should make their way into the Portland, Oregon extract as they should clearly be outside of the bounding box.

**Comment by buma** [comment]
There is also some nodes and ways from Germany in the extract from [DC Baltimore](https://mapzen.com/data/metro-extracts/#dc-baltimore-maryland)
```
 $ grep 'id="149694"' dc-baltimore_maryland.osm_01.osm 
	<way id="149694" version="4" timestamp="2013-01-24T21:57:29Z" changeset="14775106" uid="5042" user="huskytreiber">
```
[Way 149694](https://www.openstreetmap.org/way/149694). This in itself is strange but most problematic is that there are a lot of ways for which nodes doesn't exist in extract and it breaks my loading scripts.

**Comment by IndyHurt** [comment]
@dobratzp @buma this should be fixed via a [prevent element leaks](https://github.com/mapzen/chef-metroextractor/pull/18) pull request.  Check out the latest metro extracts available today (4/12/2016) and please let us know if the problem persists.

**Comment by buma** [comment]
This is definitely fixed for me in DC Baltimore extract. Thanks for the fix.
