### ISSUE TITLE
Adding a new city - Oradea, Romania

### ISSUE THREAD

**Issue by miepure** [mapzen/metroextractor-cities#439]
Oradea, Romania - https://en.wikipedia.org/wiki/Oradea
BBox: - 21.8542,47.01,22.0111,47.1166

**Comment by IndyHurt** [comment]
Hi, @miepure 
Here you go: [https://mapzen.com/data/metro-extracts/#oradea-romania](https://mapzen.com/data/metro-extracts/#oradea-romania)
