### ISSUE TITLE
UAE, DUBAI, Curbs and buildings

### ISSUE THREAD

**Issue by sara-alharbali** [mapzen/metroextractor-cities#442]
hello, i am a student at University of California, berkeley studying urban design.

i need shape files of buildings and curbs of 3 areas in the city of Dubai, United arab emirates
(currently there is buildings file that i downloaded of Dubai but it does not have all of the buildings, many buildings are missing)
(also the streets are only as center lines) but i need curbs. 

the three areas for which i need their buildings and curbs are:
Hor Al Anz and its immediate surrounding streets
International City and its surrounding highways
The greens and its surrounding streets/highways

thanks alot for your help.
regards
sara

**Comment by IndyHurt** [comment]
Hi, @sara-alharbali 
The three areas you are interested in are contained within the [Dubai Metro Extract](https://mapzen.com/data/metro-extracts/#dubai-abu-dhabi).

If buildings are missing, it could be that they don't exist in OpenStreetMap to begin with, but editors are always able to add the missing buildings.  You'll find lots of resources online to help you learn how to edit features.  Here's a great video for buildings:  [Adding a building to OpenStreetMap](https://www.youtube.com/watch?v=VPJz-AucqF4).  

Last but not least, for curbs, we don't generate curb shapefiles, but you can find the curbs in the OSM PBF files if they exist for Dubai.  Again, they will only be there if editors have added them.  The OSM PBF file is a raw data format that can be loaded into a postgres database and queried with sql.  You can then export features you query into shape files or connect directly to your database with QGIS.  (Probably ArcGIS, too.  I just haven't used ArcGIS in a long time.)

Query would be something like `select * from planet_osm_line where tags in ['kerb', 'curb'];`

OpenStreetMap uses British spelling, so you'll want to read up on [kerbs](http://wiki.openstreetmap.org/wiki/Key:kerb)
