### ISSUE TITLE
New City Addition - Mysore, India

### ISSUE THREAD

**Issue by asarma868** [mapzen/metroextractor-cities#443]
Hello,
Can you extract data for a new city - Mysore, India?

Latitude North 12.37
Latitude South 12.25
Longitude West 76.6
Longitude East 76.71

Thanks,
Amruta

**Comment by IndyHurt** [comment]
Hi, @asarma868 
Here you go [https://mapzen.com/data/metro-extracts/#mysore-india](https://mapzen.com/data/metro-extracts/#mysore-india)
