### ISSUE TITLE
Fresno County

### ISSUE THREAD

**Issue by Loprz** [mapzen/metroextractor-cities#446]
Can you please create an extract for Fresno County, California.
                "top": "37.614",
                "left": "-120.891",
                "bottom": "35.666",
                "right": "-118.337"

**Comment by IndyHurt** [comment]
Hi, @Loprz 
Currently, Mapzen's Metro Extracts only cover areas the size of cities and some larger dense metropolitan areas.  For areas larger than a metropolitan area, we recommend Geofabrik.  You may be interested in their extract for the state of [California](http://download.geofabrik.de/north-america/us/california.html).

Hope this helps!
