### ISSUE TITLE
Request to add Lucerne, Switzerland

### ISSUE THREAD

**Issue by amirmiller** [mapzen/metroextractor-cities#447]
Hope you can add shape files for Lucerne, Switzerland

**Comment by souperneon** [comment]
Hi there!
Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world. [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback by participating in a short usability study for the new experience.  [Let us know](http://goo.gl/forms/OIEdDWr7RIC04oqo2)! You can also send us your feedback anytime at [hello@mapzen.com](mailto:hello@mapzen.com)

Thanks,
Ekta.
