### ISSUE TITLE
Fresno_Clovis Metro

### ISSUE THREAD

**Issue by Loprz** [mapzen/metroextractor-cities#450]
Can you please add an extract for the Fresno-Clovis metro area. 
"bbox": {
                "top": "36.9137",
                "left": "-119.9443",
                "bottom": "36.6662",
                "right": "-119.4053"
            },

**Comment by souperneon** [comment]
Hi Ryan!
Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world. [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback by participating in a short usability study for the new experience.  [Let us know](http://goo.gl/forms/OIEdDWr7RIC04oqo2)! You can also send us your feedback anytime at [hello@mapzen.com](mailto:hello@mapzen.com)

Thanks,
Ekta.
