### ISSUE TITLE
Nimule South Sudan

### ISSUE THREAD

**Issue by darentrudeau** [mapzen/metroextractor-cities#459]
Looking for the metro and surrounding areas for Nimule, Equitorial, South Sudan

**Comment by souperneon** [comment]
Hi there, 

Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world! [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback. [Let us know](mailto:hello@mapzen.com) about the experience! 

Thanks,
Ekta.
