### ISSUE TITLE
Determining FIPS county codes for US extracts?

### ISSUE THREAD

**Issue by XPav** [mapzen/metroextractor-cities#460]
I am looking to get the associated TIGER edges data for various US cities, and those are all organized by county.   Is there an easy way to automatically determine what counties are present in a specific extract?

**Comment by migurski** [comment]
Hi, a easy way to do this is with a bounding box query against a shapefile of US counties. You can download a file from https://www.census.gov/geo/maps-data/data/cbf/cbf_counties.html, and then use [the command line program `ogr2ogr`](http://www.gdal.org/ogr2ogr.html) to select a list of counties within a bounded rectangular area, such as this request for the SF Bay Area:

    ogrinfo -al -geom=no -spat -123 37 -122 38 cb_2015_us_county_5m.shp

…which outputs:

    OGRFeature(cb_2015_us_county_5m):929
      STATEFP (String) = 06
      COUNTYFP (String) = 075
      COUNTYNS (String) = 00277302
      AFFGEOID (String) = 0500000US06075
      GEOID (String) = 06075
      NAME (String) = San Francisco
      LSAD (String) = 06
      ALAND (Real) = 121455687
      AWATER (Real) = 479135404

    OGRFeature(cb_2015_us_county_5m):1342
      STATEFP (String) = 06
      COUNTYFP (String) = 001
      COUNTYNS (String) = 01675839
      AFFGEOID (String) = 0500000US06001
      GEOID (String) = 06001
      NAME (String) = Alameda
      LSAD (String) = 06
      ALAND (Real) = 1914240928
      AWATER (Real) = 212981785

etc.
