### ISSUE TITLE
Requesting Malé, Maldives

### ISSUE THREAD

**Issue by Luuk3333** [mapzen/metroextractor-cities#464]
Boundaries:
```
"male_maldives": {
    "bbox": {
        "top": "4.2547",
        "left": "73.4295",
        "bottom": "4.1619",
        "right": "73.5569"
    }
},
```

URL: [openstreetmap.org](http://www.openstreetmap.org/#map=13/4.2139/73.4848)

Thanks!

**Comment by souperneon** [comment]
Hi Luuk!
Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world. [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback by participating in a short usability study for the new experience. [Let us know](http://goo.gl/forms/OIEdDWr7RIC04oqo2)! You can also send us your feedback anytime at [hello@mapzen.com](mailto:hello@mapzen.com)

Thanks,
Ekta.
