### ISSUE TITLE
Bremerhaven, Germany

### ISSUE THREAD

**Issue by jebume** [mapzen/metroextractor-cities#465]
I would greatly appreciate if Bremerhaven, Germany could be added to the list of cities.
Thank you
Jessica

**Comment by souperneon** [comment]
Hi Jessica!
Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world. [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback by participating in a short usability study for the new experience.  [Let us know](http://goo.gl/forms/OIEdDWr7RIC04oqo2)! You can also send us your feedback anytime at [hello@mapzen.com](mailto:hello@mapzen.com)

Thanks,
Ekta.
