### ISSUE TITLE
Ann Arbor, Michigan, USA

### ISSUE THREAD

**Issue by sampl** [mapzen/metroextractor-cities#472]
Hi, would love to see data for Ann Arbor!

```
north 42.34
south 42.20
east  -83.64
west  -83.83
```

Sam

**Comment by souperneon** [comment]
Hi Sam, 
Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world. [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback by participating in a short usability study for the new experience. [Let us know](http://goo.gl/forms/OIEdDWr7RIC04oqo2)! You can also send us your feedback anytime at [hello@mapzen.com](mailto:hello@mapzen.com)

Thanks,
Ekta.
