### ISSUE TITLE
Hello! How about Semarang, Indonesia?

### ISSUE THREAD

**Issue by emma77leah** [mapzen/metroextractor-cities#478]
Hi, there was a OSM humanitarian project here just last year so it would be nice to download just that data instead of having to work with all of Indonesia

**Comment by souperneon** [comment]
Hi there!
Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world. [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback by participating in a short usability study for the new experience. [Let us know](http://goo.gl/forms/OIEdDWr7RIC04oqo2)! You can also send us your feedback anytime at [hello@mapzen.com](mailto:hello@mapzen.com)

Thanks,
Ekta.
