### ISSUE TITLE
Adding a new city - San Salvador de Jujuy, Jujuy, Argentina

### ISSUE THREAD

**Issue by agendagauchajujuy** [mapzen/metroextractor-cities#481]
Hello.

I'd like to know if it is possible too add a new city, San Salvador de Jujuy, Jujuy, Argentina.

The coordinates are:
Latitude top: -24.150
Latitude bottom: -24.283
Longitude left: -65.406
Longitude right: -65.183

Thanks for your support.
Kind regards

**Comment by souperneon** [comment]
Hi there!
Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world! [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback by participating in a short usability study for the new experience. [Let us know](http://goo.gl/forms/OIEdDWr7RIC04oqo2)! You can also send us your feedback anytime at [hello@mapzen.com](mailto:hello@mapzen.com)

Thanks,
Ekta.
