### ISSUE TITLE
Plase add two colombian cities

### ISSUE THREAD

**Issue by danielvago** [mapzen/metroextractor-cities#484]
Dear Mapzen administrator.

I hope everything is going well. I'd like to know if it is possible too add a new city, Barranquilla, and Bucaragamanga.

The coordinates are for Barranquilla:
Latitude top: 11.0433
Latitude bottom: 10.8758
Longitude left: -74.8735
Longitude right: -74.7568

The coordinates are for Bucaramanga:
Latitude top: 7.1660
Latitude bottom: 7.0569
Longitude left: -73.0744
Longitude right: -73.1450

Thank you so much for your help I really appreciate it. 
Kind regards

**Comment by danielvago** [comment]
I just add the code in this branch https://github.com/mapzen/metroextractor-cities/compare/master...danielvago:patch-2

Thanks!!!!

**Comment by souperneon** [comment]
Hi Daniel!
Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world! [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback by participating in a short usability study for the new experience. [Let us know](http://goo.gl/forms/OIEdDWr7RIC04oqo2)! You can also send us your feedback anytime at [hello@mapzen.com](mailto:hello@mapzen.com)

Thanks,
Ekta.
