### ISSUE TITLE
Please add data for Bikaner,Rajasthan,India

### ISSUE THREAD

**Issue by Manish-Kumar94** [mapzen/metroextractor-cities#490]
Dear Admin 
Please Add City Bikaner,Rajasthan,India
The coordinates are:-

Top Latitude 29.1977
Down latitude 27.0371
left longitude 70.8865
right Longitude 75.1987

Thanx in advance

**Comment by souperneon** [comment]
Hi Manish!
Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world! [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback by participating in a short usability study for the new experience. [Let us know](http://goo.gl/forms/OIEdDWr7RIC04oqo2)! You can also send us your feedback anytime at [hello@mapzen.com](mailto:hello@mapzen.com)

Thanks,
Ekta.

**Comment by Manish-Kumar94** [comment]
Thax alot...
