### ISSUE TITLE
Cle Elum/Roslyn area

### ISSUE THREAD

**Issue by csytsma** [mapzen/metroextractor-cities#497]
Hi, it would be great to get the Central Cascades area in Washington State, USA.  West edge would be North Bend, East edge would be Wenatchee.  North Stevens Pass, South Mt Rainier.  Or split into 3 sections, North, Central, South from Canada to Oregon.

Thanks!

**Comment by souperneon** [comment]
Hi there!
Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world! [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback by participating in a short usability study for the new experience.  [Let us know](http://goo.gl/forms/OIEdDWr7RIC04oqo2)! You can also send us your feedback anytime at [hello@mapzen.com](mailto:hello@mapzen.com)

Thanks,
Ekta.
