### ISSUE TITLE
philippines data

### ISSUE THREAD

**Issue by jongf2016** [mapzen/metroextractor-cities#499]
To whom it may concern;

Good day...I humbly approach your good office to kindly provide a data shapefile for the Philippines. 'cause i have seen a lot of data osm from other Asian country and the Philippines is not included. I'm looking forward to see this available online. Please help us.

Respectfully yours,
Jong Franco

**Comment by migurski** [comment]
Hello @jongf2016, thanks for getting in touch! Countrywide data downloads are not exactly a thing that we do in this project, because there are other excellent sources of such data: http://download.geofabrik.de/asia/philippines.html

Hope that download works for you!
