### ISSUE TITLE
Need osm data for Johnson City TN

### ISSUE THREAD

**Issue by salmanyam** [mapzen/metroextractor-cities#502]
Could you please add the osm data for Johnson City TN? Thanks!

**Comment by souperneon** [comment]
Hi Salman, 

Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world! [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback. [Let us know](mailto:hello@mapzen.com) about the experience! 

Thanks,
Ekta.
