### ISSUE TITLE
Nanjing

### ISSUE THREAD

**Issue by weiqiujun** [mapzen/metroextractor-cities#507]
Nanjing,the captical of eastern Jiangsu province,is among cities with great influences in China.

**Comment by souperneon** [comment]
Hi sinα, 

Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world! [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback. [Let us know](mailto:hello@mapzen.com) about the experience! 

Thanks,
Ekta.
