### ISSUE TITLE
Chittagong, Bangladesh

### ISSUE THREAD

**Issue by zamanf** [mapzen/metroextractor-cities#508]
Chittagong is one of the oldest Port cities of the World!

It has  great influences in Bangladesh and South Asia!!

**Comment by souperneon** [comment]
Hi Fokhruz, 

Thank you for your request. 
At Mapzen, we just introduced an on-demand feature to make it easier and faster get custom extracts of places all over the world! [Give it a try](https://mapzen.com/data/metro-extracts-alt/)!

We are still testing it with people and would love it if you could give us your feedback. [Let us know](mailto:hello@mapzen.com) about the experience! 

Thanks,
Ekta.
